### ISSUE TITLE
array-vec insufficient capacity when serializing w/ bincode

### ISSUE THREAD

**Issue by blasrodri** [paupino/rust-decimal#317]
Hi! We noticed that when using version `1.10.2` the following snippet breaks:

```rust
use rust_decimal_macros::*;
use rust_decimal::prelude::*;

fn main() {
    let d = dec!(-5233.9008808150288439427720175);
    dbg!(d);
    let s = bincode::serialize(&d).unwrap();
    let dd: Decimal = bincode::deserialize(&s).unwrap();
    assert_eq!(dd, dec!(-5233.9008808150288439427720175));
}
```

Deps:

```toml
[dependencies]
#rust_decimal_macros = { version = "=1.9.0" }
#rust_decimal= { version = "=1.9.0", features= ["serde-bincode"] }

rust_decimal_macros = { version = "1.10.2" }
rust_decimal= { version = "1.10.2", features= ["serde-bincode"] }

bincode = "1.2.0"
```

```bash
b@layer-two:~/Downloads/delete_me$ cargo run
   Compiling delete_me v0.1.0 (/home/b/Downloads/delete_me)
    Finished dev [unoptimized + debuginfo] target(s) in 0.49s
     Running `target/debug/delete_me`
[src/main.rs:6] d = -5233.9008808150288439427720175
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CapacityError: insufficient capacity', /home/b/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayvec-0.5.2/src/array_string.rs:165:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It doesn't happen with `1.9.0`
