### ISSUE TITLE
Roundtrip using "serde-float" and "serde-arbitrary-precision" fails

### ISSUE THREAD

**Issue by JamesHinshelwood** [paupino/rust-decimal#402]
The assertion in the following code fails, whereas I would expect it to succeed based on the features I have activated:

`main.rs`:
```rust
use rust_decimal::Decimal;

fn main() {
    let dec = Decimal::new(481, 2);
    let serialized = serde_json::to_value(dec).unwrap();
    let dec2: Decimal = serde_json::from_value(serialized).unwrap();

    assert_eq!(dec, dec2);
}
```

`Cargo.toml`:
```toml
[package]
name = "rust_decimal_test"
version = "0.1.0"
authors = ["..."]
edition = "2018"

[dependencies]
rust_decimal = { version = "1.14.3", features = ["serde-float", "serde-arbitrary-precision"]}
serde_json = { version = "1.0.64", features = ["arbitrary_precision"] }
```

Output:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `4.81`,
 right: `4.8100000000000005`', src/main.rs:8:5
```

Reading the documentation of `serde-arbitrary-precision` further, it makes it clear that it only supports arbitrary precision when *parsing* decimals but not when serializing them. `.to_f64()` is still used in the `Serialize` impl which causes the rounding issue.

Would you be opposed to extending the behaviour of the `serde-arbitrary-precision` feature to also serialize `Decimal`s to JSON numbers exactly, so that the above test would pass?

I'd be willing to attempt to contribute this change if you thought it was a good idea.

**Comment by JamesHinshelwood** [comment]
I've raised a #404 for an attempt at fixing this. Let me know what you think!

**Comment by paupino** [comment]
Hi @JamesHinshelwood,
Thanks for issue write up and for publishing the PR! 
I think that this area of the library is actually quite confusing and could do with some clearer documentation/examples - perhaps later flattening features. Anyway, can you try one thing for me? Can you _remove_ the `serde-float` feature and see if that solves your issues? e.g.

```toml
[package]
name = "rust_decimal_test"
version = "0.1.0"
authors = ["..."]
edition = "2018"

[dependencies]
rust_decimal = { version = "1.14.3", features = ["serde-arbitrary-precision"]}
serde_json = { version = "1.0.64", features = ["arbitrary_precision"] }
```

Or is your issue with the format that it is being serialized to when using `serde-arbitrary-precision` (hence also using `serde-float`)?
