### ISSUE TITLE
Deserializing json strings and floats while also allowing bincode roundtrips

### ISSUE THREAD

**Issue by jenanwise** [paupino/rust-decimal#420]
I have an application that needs to support the following:

1. deserialize `serde-float`-style json with arbitrary precision, e.g. `{"dec": 4.81}`
2. deserialize `serde-str`-style json, e.g. `{"dec": "4.81"}`
3. rountrip `Decimal` values through `bincode`

As far as I can tell, there is no combination of the `serde-*` feature flags that enables this directly:

- `serde-arbitrary-precision` alone enables (1) and (2), but breaks (3)
- `serde-arbitrary-precision` + `serde-str` enables (2) and (3) but breaks (1)

The best I could come up with was to use `serde-arbitrary-precision` + `serde-str` and annotate (1) with a custom deserializer:

```rust
use rust_decimal::Decimal;
use serde::{Deserialize, Deserializer};
use std::str::FromStr;

fn main() {
    let dec = Decimal::from_str("1.1234127836128763").unwrap();

    // Roadtrip a Decimal with bincode.
    let bytes = bincode::serialize(&dec).unwrap();
    let dec_in: Decimal = bincode::deserialize(&bytes).unwrap();
    assert_eq!(dec_in, dec);

    // Deserialize both string and raw number formats from json.
    let foo1: Foo1 = serde_json::de::from_str(r#"{"dec": "1.1234127836128763"}"#).unwrap();
    let foo2: Foo2 = serde_json::de::from_str(r#"{"dec": 1.1234127836128763}"#).unwrap();
    assert_eq!(foo1.dec, dec);
    assert_eq!(foo2.dec, dec);
}

#[derive(Deserialize)]
struct Foo1 {
    dec: Decimal,
}

#[derive(Deserialize)]
struct Foo2 {
    #[serde(deserialize_with = "decimal_raw_number_deserializer")]
    dec: Decimal,
}

pub fn decimal_raw_number_deserializer<'de, D>(deserializer: D) -> Result<Decimal, D::Error>
where
    D: Deserializer<'de>,
{
    let num = serde_json::Number::deserialize(deserializer)?;
    Decimal::from_str(&num.to_string()).map_err(serde::de::Error::custom)
}
```
```toml
[package]
name = "rust_decimal_serde_multi_format_issue"
version = "0.1.0"
edition = "2018"

[dependencies]
bincode = "1.3.3"
 rust_decimal = { version = "1.15.0", features = ["serde-str", "serde-arbitrary-precision"]}
serde_json = { version = "1.0.66", features = ["arbitrary_precision"]}
serde = { version = "1.0.129", features = ["derive"] }
```
Is this the best way to achieve this?
