### ISSUE TITLE
`serde-with-str` does not work with bincode, unlike `serde-str`

### ISSUE THREAD

**Issue by jenanwise** [paupino/rust-decimal#483]
The `serde-with-*` features were added in #459, adding field-level control. However, it seems that the `serde-with-str` feature uses `deserialize_any`, _unlike_ `serde-str`. This makes it incompatible with `bincode`.

`Cargo.toml`:

```toml
[package]
name = "rust_decimal_version_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rust_decimal = { version = "1.21.0", features = ["serde-with-str"] }
serde = { version = "1.0.136", features = ["derive"] }
```

`main.rs`:

```rust
#[derive(Debug, serde::Deserialize, serde::Serialize)]
struct Foo {
    #[serde(with = "rust_decimal::serde::str")]
    dec: rust_decimal::Decimal,
}
fn main() {
    let val = Foo {
        dec: rust_decimal::Decimal::ONE,
    };
    let bytes = bincode::serialize(&val).unwrap();
    let _deserialized: Foo = bincode::deserialize(&bytes).unwrap();
}
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeserializeAnyNotSupported', src/main.rs:11:59
```

Switching to `rust_decimal = { version = "1.21.0", features = ["serde-str"] }` and removing the `#[serde(with = ...)]` annotation makes the above case work.

Is it correct that these features should behave the same, except for the `with` variant being field-level?
